---
- hosts: exemple-1
  remote_user: root
  tasks:
    - name: Installation de nginx web server
      package:
        name: nginx
        state: installed
      notify:
        - start nginx
    - name: Modification du template principale
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.nginx-debian.html
        
  handlers:
    - name: start nginx
      service:
        name: nginx
        state: started
